server:
  port: 5160
spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  profiles:
    active: test
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  main:
    allow-circular-references: true

#websocket
websocket:
  port: 8880

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:/mapper/**/*.xml

jwt:
  secret: VaccineDispenser
  expiration: 86400
  tokenHead: Bearer

com:
  com1: COM10
  com2: COM9
  com3: COM4
  enable: true

camera:
  above: 160.160.160.11
  below: 160.160.160.12
  side:  160.160.160.13
  enable: true



logging:
  level:
    com.yiwan.vaccinedispenser.system.sys.dao: warn
    root: info


