
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:mysql://127.0.0.1:3306/vaccine_dispenser_qinggang?useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&characterEncoding=utf8
#    url: jdbc:mysql://127.0.0.1:3306/vaccine_dispenser_puyan?useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&characterEncoding=utf8
    url: jdbc:mysql://127.0.0.1:3306/vaccine_dispenser_shounan?useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
      maximum-pool-size: 100
      max-lifetime: 1800000
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 10
    timeout: 5000
    jedis:
      pool:
        max-wait: 2000
        min-idle: 2
        max-idle: 8
        max-active: 8
  servlet:
    multipart:
      enabled: true
      max-request-size: 100MB
      max-file-size: 100MB

netty:
  enable: false

plc:
  enable: true
  auto-start: true
  host: 192.168.1.6
  port: 502
  connect-timeout: 3000
  re-connect-delay: 3000
  max-retry: 10
  poll-enabled: true
  alarm-poll-enabled: false
  #机器手模式
  handle-mode: true

plc-webvisu:
  url: http://192.168.1.6:8080/webvisu.htm


app:
  apiKey: 905121470
  privateKeyPath: ./yiwan-vaccinedispenser-admin/src/main/resources/private_key.pem
  isOpen: false
  sendIsOpen: false
  apiEnvironment: http://59.202.53.246/open/api
  version: 1.0.0

pdf:
  fontPath: ./yiwan-vaccinedispenser-admin/src/main/resources/fonts/simsun.ttf

upload:
  hospitalName: 拱宸桥
  uploadPath: http://47.97.48.26:5080
  databaseName: vaccine_dispenser_gongchenqiao
  password: gcq123
